language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t nalinhb/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true nalinhb/docker-react npm run test